version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oj-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO=mongodb+srv://aditya:aditya@cluster0.pr4dtze.mongodb.net/online-judge?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=aditya8778
      - ADMIN_SECRET_CODE=aditya8778
      - PORT=3000
    networks:
      - app-network
    # Simpler health check - just check if port is responding
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s

  backend:
    build: ./backend
    container_name: oj-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGO=mongodb+srv://aditya:aditya@cluster0.pr4dtze.mongodb.net/online-judge?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=aditya8778
      - ADMIN_SECRET_CODE=aditya8778
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge