version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: oj-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=oj

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oj-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/oj
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: oj-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    depends_on:
      - api
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge